#!/bin/sh
cd ..
GIT_DIR='.git'
DOMAIN=$(basename $(pwd))
umask 002 && git reset --hard
git clean -f
git checkout master
git branch -D prod
npm install
echo "Starting the container..."
curl --silent --unix-socket /var/run/docker.sock -X POST "http:/localhost/containers/${DOMAIN}/restart"
echo "Your app is running at https://${DOMAIN}"
