#!/bin/sh
cd ..
GIT_DIR='.git'
umask 002 && git reset --hard
git clean -f
git checkout master
git branch -D prod
npm install
sudo -u myproxy pm2 startOrRestart deploy.config.js --env production --update-env
